= JSON to JSON transformation policy

ifdef::env-github[]
image:https://img.shields.io/static/v1?label=Available%20at&message=Gravitee.io&color=1EC9D2["Gravitee.io", link="https://download.gravitee.io/#graviteeio-apim/plugins/policies/gravitee-policy-json-to-json/"]
image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["License", link="https://github.com/gravitee-io/gravitee-policy-json-to-json/blob/master/LICENSE.txt"]
image:https://img.shields.io/badge/semantic--release-conventional%20commits-e10079?logo=semantic-release["Releases", link="https://github.com/gravitee-io/gravitee-policy-json-to-json/releases"]
image:https://circleci.com/gh/gravitee-io/gravitee-policy-json-to-json.svg?style=svg["CircleCI", link="https://circleci.com/gh/gravitee-io/gravitee-policy-json-to-json"]
endif::[]

== Scope

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^| X

|===

== Description

You can use the `json-to-json` policy to apply a transformation (or mapping) on the request and/or response content.

This policy is based on the https://github.com/bazaarvoice/jolt[JOLT^] library.
In APIM, you need to provide the JOLT specification
in the policy configuration.

== Configuration

You can configure the policy with the following options:

|===
|Property |Required |Description |Type| Default

.^|scope
^.^|X
|The execution scope (`request` or `response`)
^.^|string
^.^|`REQUEST`

.^|specification
^.^|X
|The http://jolt-demo.appspot.com/[JOLT^] specification to apply on a given content
^.^|string
^.^|

|===

Example configuration:

[source, json]
----
"json-to-json": {
    "scope": "REQUEST",
    "specification": "[\n  {\n    \"operation\": \"shift\",\n    \"spec\": {\n      \"_id\": \"id\",\n      \"*\": {\n        \"$\": \"&1\"\n      }\n      \n    }\n  },\n  {\n    \"operation\": \"remove\",\n    \"spec\": {\n      \"__v\": \"\"\n    }\n  }\n]\n"
}
----

== Examples

For this input:

[source, json]
.Input
----
{
    "_id": "57762dc6ab7d620000000001",
    "name": "name",
    "__v": 0
}
----

And this JOLT specification:

[source, json]
----
[
  {
    "operation": "shift",
    "spec": {
      "_id": "id",
      "*": {
        "$": "&1"
      }
    }
  },
  {
    "operation": "remove",
    "spec": {
      "__v": ""
    }
  }
]
----

The output is as follows:

[source, json]
----
{
    "id": "57762dc6ab7d620000000001",
    "name": "name"
}
----

== Errors

=== HTTP status code

|===
|Code |Message

.^| ```500```
| Bad specification file or transformation cannot be executed properly

|===
