= JSON to JSON transformation policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-json-to-json/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-json-to-json/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Scope

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^| X

|===

== Description

You can use the `json-to-json` policy to apply a transformation (or mapping) on the request and/or response content.

This policy is based on the https://github.com/bazaarvoice/jolt[JOLT^] library.
In APIM, you need to provide the JOLT specification
in the policy configuration.

== Configuration

You can configure the policy with the following options:

|===
|Property |Required |Description |Type| Default

.^|scope
^.^|X
|The execution scope (`request` or `response`)
^.^|string
^.^|`REQUEST`

.^|specification
^.^|X
|The http://jolt-demo.appspot.com/[JOLT^] specification to apply on a given content
^.^|string
^.^|

|===

Example configuration:

[source, json]
----
"json-to-json": {
    "scope": "REQUEST",
    "specification": "[\n  {\n    \"operation\": \"shift\",\n    \"spec\": {\n      \"_id\": \"id\",\n      \"*\": {\n        \"$\": \"&1\"\n      }\n      \n    }\n  },\n  {\n    \"operation\": \"remove\",\n    \"spec\": {\n      \"__v\": \"\"\n    }\n  }\n]\n"
}
----

== Examples

For this input:

[source, json]
.Input
----
{
    "_id": "57762dc6ab7d620000000001",
    "name": "name",
    "__v": 0
}
----

And this JOLT specification:

[source, json]
----
[
  {
    "operation": "shift",
    "spec": {
      "_id": "id",
      "*": {
        "$": "&1"
      }
    }
  },
  {
    "operation": "remove",
    "spec": {
      "__v": ""
    }
  }
]
----

The output is as follows:

[source, json]
----
{
    "id": "57762dc6ab7d620000000001",
    "name": "name"
}
----

== Errors

=== HTTP status code

|===
|Code |Message

.^| ```500```
| Bad specification file or transformation cannot be executed properly

|===
